# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Chat_pb2 as Chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMessage = channel.unary_unary(
        '/Chat/SendMessage',
        request_serializer=Chat__pb2.Message.SerializeToString,
        response_deserializer=Chat__pb2.Estado.FromString,
        )
    self.ReciveMessage = channel.unary_stream(
        '/Chat/ReciveMessage',
        request_serializer=Chat__pb2.Id.SerializeToString,
        response_deserializer=Chat__pb2.Message.FromString,
        )
    self.Ping = channel.unary_unary(
        '/Chat/Ping',
        request_serializer=Chat__pb2.Pong.SerializeToString,
        response_deserializer=Chat__pb2.Pong.FromString,
        )
    self.Connection = channel.unary_unary(
        '/Chat/Connection',
        request_serializer=Chat__pb2.Nombre.SerializeToString,
        response_deserializer=Chat__pb2.Id.FromString,
        )
    self.New_message = channel.unary_unary(
        '/Chat/New_message',
        request_serializer=Chat__pb2.Id.SerializeToString,
        response_deserializer=Chat__pb2.NewMessageID.FromString,
        )
    self.Messages = channel.unary_unary(
        '/Chat/Messages',
        request_serializer=Chat__pb2.Id.SerializeToString,
        response_deserializer=Chat__pb2.MessageList.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReciveMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Connection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def New_message(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Messages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=Chat__pb2.Message.FromString,
          response_serializer=Chat__pb2.Estado.SerializeToString,
      ),
      'ReciveMessage': grpc.unary_stream_rpc_method_handler(
          servicer.ReciveMessage,
          request_deserializer=Chat__pb2.Id.FromString,
          response_serializer=Chat__pb2.Message.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=Chat__pb2.Pong.FromString,
          response_serializer=Chat__pb2.Pong.SerializeToString,
      ),
      'Connection': grpc.unary_unary_rpc_method_handler(
          servicer.Connection,
          request_deserializer=Chat__pb2.Nombre.FromString,
          response_serializer=Chat__pb2.Id.SerializeToString,
      ),
      'New_message': grpc.unary_unary_rpc_method_handler(
          servicer.New_message,
          request_deserializer=Chat__pb2.Id.FromString,
          response_serializer=Chat__pb2.NewMessageID.SerializeToString,
      ),
      'Messages': grpc.unary_unary_rpc_method_handler(
          servicer.Messages,
          request_deserializer=Chat__pb2.Id.FromString,
          response_serializer=Chat__pb2.MessageList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
