# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nChat.proto\"\x18\n\x06Nombre\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"\x10\n\x02Id\x12\n\n\x02id\x18\x02 \x01(\x05\"\"\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\"\x1f\n\x08UserList\x12\x13\n\x04user\x18\x01 \x03(\x0b\x32\x05.User\"k\n\x07Message\x12\x15\n\x06\x65misor\x18\x01 \x01(\x0b\x32\x05.User\x12\x11\n\tcontenido\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x17\n\x08receptor\x18\x05 \x01(\x0b\x32\x05.User\"\x1a\n\x0cNewMessageID\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x0bMessageList\x12\x15\n\x03msn\x18\x01 \x03(\x0b\x32\x08.Message\"\x14\n\x04Pong\x12\x0c\n\x04ping\x18\x01 \x01(\t\")\n\x06\x45stado\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x08\x12\x0f\n\x07\x64\x65talle\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xe1\x01\n\x04\x43hat\x12 \n\x0bSendMessage\x12\x08.Message\x1a\x07.Estado\x12 \n\rReciveMessage\x12\x03.Id\x1a\x08.Message0\x01\x12\x14\n\x04Ping\x12\x05.Pong\x1a\x05.Pong\x12\x1a\n\nConnection\x12\x07.Nombre\x1a\x03.Id\x12!\n\x0bNew_message\x12\x03.Id\x1a\r.NewMessageID\x12\x1d\n\x08Messages\x12\x03.Id\x1a\x0c.MessageList\x12!\n\x0fListaDeUsuarios\x12\x03.Id\x1a\t.UserListb\x06proto3')
)




_NOMBRE = _descriptor.Descriptor(
  name='Nombre',
  full_name='Nombre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='Nombre.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=38,
)


_ID = _descriptor.Descriptor(
  name='Id',
  full_name='Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Id.id', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=56,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nombre', full_name='User.nombre', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=92,
)


_USERLIST = _descriptor.Descriptor(
  name='UserList',
  full_name='UserList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='UserList.user', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=125,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emisor', full_name='Message.emisor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Message.contenido', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Message.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='Message.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receptor', full_name='Message.receptor', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=234,
)


_NEWMESSAGEID = _descriptor.Descriptor(
  name='NewMessageID',
  full_name='NewMessageID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='NewMessageID.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=262,
)


_MESSAGELIST = _descriptor.Descriptor(
  name='MessageList',
  full_name='MessageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msn', full_name='MessageList.msn', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=300,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ping', full_name='Pong.ping', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=322,
)


_ESTADO = _descriptor.Descriptor(
  name='Estado',
  full_name='Estado',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='estado', full_name='Estado.estado', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detalle', full_name='Estado.detalle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=365,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=374,
)

_USERLIST.fields_by_name['user'].message_type = _USER
_MESSAGE.fields_by_name['emisor'].message_type = _USER
_MESSAGE.fields_by_name['receptor'].message_type = _USER
_MESSAGELIST.fields_by_name['msn'].message_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Nombre'] = _NOMBRE
DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserList'] = _USERLIST
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['NewMessageID'] = _NEWMESSAGEID
DESCRIPTOR.message_types_by_name['MessageList'] = _MESSAGELIST
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['Estado'] = _ESTADO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nombre = _reflection.GeneratedProtocolMessageType('Nombre', (_message.Message,), {
  'DESCRIPTOR' : _NOMBRE,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Nombre)
  })
_sym_db.RegisterMessage(Nombre)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Id)
  })
_sym_db.RegisterMessage(Id)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

UserList = _reflection.GeneratedProtocolMessageType('UserList', (_message.Message,), {
  'DESCRIPTOR' : _USERLIST,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:UserList)
  })
_sym_db.RegisterMessage(UserList)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

NewMessageID = _reflection.GeneratedProtocolMessageType('NewMessageID', (_message.Message,), {
  'DESCRIPTOR' : _NEWMESSAGEID,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:NewMessageID)
  })
_sym_db.RegisterMessage(NewMessageID)

MessageList = _reflection.GeneratedProtocolMessageType('MessageList', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGELIST,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:MessageList)
  })
_sym_db.RegisterMessage(MessageList)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Pong)
  })
_sym_db.RegisterMessage(Pong)

Estado = _reflection.GeneratedProtocolMessageType('Estado', (_message.Message,), {
  'DESCRIPTOR' : _ESTADO,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Estado)
  })
_sym_db.RegisterMessage(Estado)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=377,
  serialized_end=602,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='Chat.SendMessage',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_ESTADO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReciveMessage',
    full_name='Chat.ReciveMessage',
    index=1,
    containing_service=None,
    input_type=_ID,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='Chat.Ping',
    index=2,
    containing_service=None,
    input_type=_PONG,
    output_type=_PONG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Connection',
    full_name='Chat.Connection',
    index=3,
    containing_service=None,
    input_type=_NOMBRE,
    output_type=_ID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='New_message',
    full_name='Chat.New_message',
    index=4,
    containing_service=None,
    input_type=_ID,
    output_type=_NEWMESSAGEID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Messages',
    full_name='Chat.Messages',
    index=5,
    containing_service=None,
    input_type=_ID,
    output_type=_MESSAGELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListaDeUsuarios',
    full_name='Chat.ListaDeUsuarios',
    index=6,
    containing_service=None,
    input_type=_ID,
    output_type=_USERLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
